//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clienteMiServicioWeb2.clienteMiServicioWeb {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Mensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContenidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contenido {
            get {
                return this.ContenidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenidoField, value) != true)) {
                    this.ContenidoField = value;
                    this.RaisePropertyChanged("Contenido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito {
            get {
                return this.ExitoField;
            }
            set {
                if ((this.ExitoField.Equals(value) != true)) {
                    this.ExitoField = value;
                    this.RaisePropertyChanged("Exito");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="clienteMiServicioWeb.IMiServicioWeb")]
    public interface IMiServicioWeb {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicioWeb/eco", ReplyAction="http://tempuri.org/IMiServicioWeb/ecoResponse")]
        clienteMiServicioWeb2.clienteMiServicioWeb.Mensaje eco(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicioWeb/eco", ReplyAction="http://tempuri.org/IMiServicioWeb/ecoResponse")]
        System.Threading.Tasks.Task<clienteMiServicioWeb2.clienteMiServicioWeb.Mensaje> ecoAsync(string mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiServicioWebChannel : clienteMiServicioWeb2.clienteMiServicioWeb.IMiServicioWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiServicioWebClient : System.ServiceModel.ClientBase<clienteMiServicioWeb2.clienteMiServicioWeb.IMiServicioWeb>, clienteMiServicioWeb2.clienteMiServicioWeb.IMiServicioWeb {
        
        public MiServicioWebClient() {
        }
        
        public MiServicioWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiServicioWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public clienteMiServicioWeb2.clienteMiServicioWeb.Mensaje eco(string mensaje) {
            return base.Channel.eco(mensaje);
        }
        
        public System.Threading.Tasks.Task<clienteMiServicioWeb2.clienteMiServicioWeb.Mensaje> ecoAsync(string mensaje) {
            return base.Channel.ecoAsync(mensaje);
        }
    }
}
